---
inherit_mode:
  merge:
    - Exclude
    - IgnoredMethods

plugins: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"

# Layout
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace


# Metrics
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15
  CountAsOne: [hash, array, method_call, heredoc]

Metrics/ModuleLength:
  CountAsOne: [hash, array, method_call, heredoc]


# Rubocop
RSpec/ExampleLength:
  Max: 10
  CountAsOne: [hash, array, method_call, heredoc]


# Rails
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
    - qa
